### ISSUE TITLE
Kernel crashes when using with latest release of robotframework (6.1.0)

### ISSUE THREAD

**Issue by sanderploegsma** [robots-from-jupyter/robotkernel#143]
Can be reproduced by launching a Binder with the following environment configuration:

``` yaml
name: robotkernel-repro

channels:
  - conda-forge

dependencies:
  - jupyterlab>=3,<4
  - jupyterlab_robotmode
  - numpy
  - pip
  - pip:
      - robotframework==6.1.0
      - robotkernel==1.6
  - python>=3.9,<3.11
```

When attempting to start the kernel it crashes due to an import error:

```
[I 2023-07-13 06:45:03.807 SingleUserLabApp restarter:72] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/conda/envs/notebook/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/robotkernel/kernel.py", line 10, in <module>
    from robotkernel.executors import execute_python
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/robotkernel/executors.py", line 9, in <module>
    from robotkernel.builders import build_suite
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/robotkernel/builders.py", line 6, in <module>
    from robotkernel.builders_32 import build_suite
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/robotkernel/builders_32.py", line 5, in <module>
    from robot.running.builder.parsers import ErrorReporter
ImportError: cannot import name 'ErrorReporter' from 'robot.running.builder.parsers' (/srv/conda/envs/notebook/lib/python3.10/site-packages/robot/running/builder/parsers.py)
```

**Comment by JFoederer** [comment]
the ErrorReporter class has been removed from Robot Framework with this commit:
https://github.com/robotframework/robotframework/commit/19a8f7b72a6d62850b63ad98cfdfe0ef20c2bfa3#diff-62ecb8a491822441896f065a247b7fa24bd0f07d87787fe9af499a694a056c7e

**Comment by datakurre** [comment]
@sanderploegsma Thanks for the report!

**Comment by datakurre** [comment]
Been working on this at https://github.com/robots-from-jupyter/robotkernel/pull/144 

Branch https://github.com/robots-from-jupyter/robotkernel/tree/rf61 probably works now, but I still have a few CI issues to fix before merge, manual acceptance testing and release. (Jupyter Lite build to Read The Docs is broken, and binder build is broken due to some un-pinned build changes.)

**Comment by datakurre** [comment]
Keyword buttons seem to be broken with the latest JupyterLab and Jupyter Widgets. I'll create a new issue and will delay next release until that is fixed.
