### ISSUE TITLE
Getting error trying to install with pip on python 2.7

### ISSUE THREAD

**Issue by vangheem** [robots-from-jupyter/robotkernel#15]
distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]`

**Comment by vangheem** [comment]
using setuptools==39.1.0

**Comment by datakurre** [comment]
pip install -U setuptools

**Comment by datakurre** [comment]
> distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.data_files]`

This errors is because I use declarative packaging (`setup.cfg`) and `options.data_files` only became supported in  setuptools 40.5.0. Yet, I wanted to add it, because it allows Jupyter to find robotkernel automatically after pip install in most use cases.

**Comment by datakurre** [comment]
@vangheem Was there some specific reason for trying this with Python 2.7?

If some Python 2.7 software were to be robot tested and it would help to have "Python compatibility", a common workaround is to implement "remote keyword library" for Python 2.7 software.

* https://github.com/robotframework/RemoteInterface
* https://github.com/robotframework/PythonRemoteServer

**Comment by vangheem** [comment]
I guess really, there probably isn't a reason why I am using 2.7 for this. It was just part of the environment I was playing with. I'll close.

**Comment by vangheem** [comment]
actually yah, I guess I will need py 2.7 because I'll need to import keywords from that environment
