### ISSUE TITLE
Keyword execution widgets are saved with notebook and are loaded as broken

### ISSUE THREAD

**Issue by datakurre** [robots-from-jupyter/robotkernel#20]
@bollwyvl If you have time, I'd have a question related to widgets.

I implemented naive Jupyter widgets based keyword execution feature. It's currently available at master and can be seen with binder: https://mybinder.org/v2/gh/robots-from-jupyter/robotkernel/master?urlpath=lab/tree/example.ipynb

When user "executes" a cell with Robot keywords, there will be buttons for setting parameters and executing generated test/task with just that keyword. That works well and should make RobotLab more useful for writing keyword resource files.

The problem is that now those will pollute saved notebooks. It seems lab does not properly save widget states yet. Notebook can, but because those widgets rely on kernel state they will still load broken. Also I have not found any way to completely clear the widgets (I was able to add an extra button to clear the widgets themselves, but the notebook did still contain empty output areas for widgets and their outputs).

Would you have ideas, how should I implement this properly or a way to completely remove widget output areas from the notebook (with kernel code, without JS)?

**Comment by datakurre** [comment]
https://www.youtube.com/watch?v=I0itWfQWnB8

**Comment by bollwyvl** [comment]
Looks fantastic. I'll take a look at the code and see if I see anything
obvious that might help.

The mental model is pretty weird... The notepad example has so much hidden
state, I don't know how I would repeatably add that... in the near term,
perhaps you could make a keyword that showed a widget, for a given thing
e.g.

*** Settings ***
Library  IPyRobotWidgetsLibrary

*** Tasks ***
Interactive Robot
    Interact with Keyword ...
    Interact with Library ...
    Interact with Resource ...
    Interact with Suite ...

If you toss one of these into a normal test, you could also do some waiting
conditions and stuff.

As to saving state:

 Maarten did an example extension:

https://github.com/maartenbreddels/jupyterlab-supersave

However, "Configurable save with state" (not just widgets, also collapsed,
etc) will land in core in the next lab release.

There's a lot you can't do from the kernel side concerning widget front-end
plumbing, so you either have to roll up your sleeves and implement it, or
spit out something that doesn't make it complain.

once this is resolved, though, I could definitely see putting the whole
test suite run process on the widget bus, as you could implement cool stuff
like "pause".

However, on a completely different track, I did an extension for
jupyterlab-commenting that put the suite/resource in over in that left
area. I just about got to running them, but might be worth doing. It used a
much dirtier approach than widgets, just running code like the bad old days
with kernel.execute. widgets would be better.

**Comment by datakurre** [comment]
@bollwyvl Thanks. I'm happy enough to know the limits, get some good examples and then figure out my way to get those widgets behave.

My "keyword widgets' state" is basically a generated test suite, so maybe there's a way to pass that as a string all they way to the widget state.

Minimally I would like to find a way to remove those widget completely (without removing all the other output) before save, but that sounds like that could be hard thing to do without custom front end code :-)

**Comment by datakurre** [comment]
I close this now as "wontfix" and return to this once JupyterLab has stable release with stable widgets support.

I guess, "keyword execution widget" could be serialized into a call to module level function parameterized with with full robot framework test suite as a string.

For now I implemented "toggling" of widgets so that the first execution of keyword cell shows the widgets and second execution with the same cell contents will hide them, and so on. That is enough to allow hiding of widgets before saving a notebook.
