### ISSUE TITLE
Pick a mime type?

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotkernel#40]
So the back story of why [jupter_lsp](https://github.com/krassowski/jupyterlab-lsp/issues/189) wants to talk over `text/plain`: it's what the [kernel says it wants](https://github.com/robots-from-jupyter/robotkernel/blob/17739044255cd298bb02a2c4a54142fccc650e61/src/robotkernel/kernel.py#L53)!

While we'll go ahead and try to do a better job on that end, discrete mime types, even if they are not defined by the IANA, certainly help a lot as they have the _intent_ to aid in machine-level integration. I don't want to put this all on `robotkernel`, as it would no doubt benefit the whole community, but...

**Comment by datakurre** [comment]
🙈

**Comment by datakurre** [comment]
Fixed in https://github.com/robots-from-jupyter/robotkernel/commit/2aef02f4fca34b2b47938fd507014682161871c6
