### ISSUE TITLE
Docker Image Permissions for RobotKernel

### ISSUE THREAD

**Issue by teaglebuilt** [robots-from-jupyter/robotkernel#45]
Hey I noticed you have configured a user for the image and there are permissions in the opt volume which conflicts with python packages as they install. If I add a dependency that is already installed with robotkernel, but is an updated version, it will throw the permissions error when pip is attempting to uninstall the package from /opt/jupyter/bin, to reinstall an updated version of the dependency.

Is there a way we can change this or is there a reason for this that i am missing?

**Comment by datakurre** [comment]
@teaglebuilt Dockerfile is most probably out of date. I might not have updated it since Nick pointed me to use binder for demo instead. So, please, assume that Dockerfile is broken and if you find issues, you are probably correct.

**Comment by teaglebuilt** [comment]
Ok. Is it alright if I submit a pull request?

**Comment by teaglebuilt** [comment]
I just used pip to install the kernel module as a package onto jupyters base image.
