### ISSUE TITLE
Add RF 3.2 parser features to syntax highlighting

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotkernel#47]
I've barely dug into the RF 3.2 CHANGELOG for new syntax features, but it's probably worth revisiting at this point. For example, I noted that `${{ any.old.python() }}` is a (terrifying) thing.

**Comment by bollwyvl** [comment]
This is now generally available (along with `IF` from https://github.com/MarketSquare/jupyterlab_robotmode)!

**Comment by datakurre** [comment]
That reminds me that I should make a release. The master works with RF 4.0.x already.

**Comment by bollwyvl** [comment]
Also, how you been?!

**Comment by datakurre** [comment]
Aside from slowly getting crazy by working at "safe shared home office" for the last 14 months, been working a lot around Camunda for orchestrating both humans and robots. 

* Low code process digitizing platform (still WIP): http://datakurre.pandala.org/2020/05/vasara-bpm-open-source-mashup/
* Helping users through complex epics with Camunda: http://datakurre.pandala.org/2021/03/implementing-user-epics-bpmn-plone-volto/
* Automating Camunda tasks with Robot Framework: https://gitlab.com/atsoukka/robot-rpa-playground/
* Building a FaaS for that: http://datakurre.pandala.org/2021/04/camunda-nomad-robotframework-rpa/

How are you? Just yesterday shared one more time your old RF Blocky demo.

**Comment by bollwyvl** [comment]
> orchestrating both humans and robots.

Those look rad. I see a lot of benefit to science in having solid open-source, on-prem tooling. It's cool you've been working with hasura... i'd love to get a chance to work with that stack. In a JupyterHub setting, I could see hasura as the "heavy duty" OLTP side of the house for an organization's bespoke domain data, and use the schema federation stuff (available from a few GraphQL servers) to tie in other related resources: e.g. available packages from your package repository, meetings in your calendar, datasets in your data catalog, runs of your pipelines. I'm really interested in [dagster](https://github.com/dagster-io/dagster), and have done a few small, stumbling steps towards integrating that into a hub, with this [binder](https://gist.github.com/bollwyvl/0fe7a6f89251992ab1a542ac2b4051c4).

Regarding "orchestrating people": we've all had to deal more with telepresence, and we've been working on [jupyter-videochat](https://github.com/yuvipanda/jupyter-videochat), currently only backed by Jitsi. I'm hoping to start (ab)using their XMPP bus to build some pretty things, starting with polls, but working up to breakout rooms, drawio, etc. and integrating them into computable artifacts.

On the diagram front: your stack looks really nice, and you didn't have to do too much of it, which is a big win. I'm always stuck having to either do stuff that diagram packages don't know, or don't scale, or whatever.

Just a couple weeks ago dropped a lab-3 compatible version of [ipydrawio](https://github.com/deathbeds/ipydrawio) which ships with pretty rich _pictures_ (not so much _models_) which include some of the glyphs needed there. It's the first thing i've done that (almost) correctly abstracted out the model from the Big Three renderers in lab (MIME, Jupyter Widget, Document). We've also been working on [ipyelk](https://github.com/jupyrdf/ipyelk) which has the best open source layout engine out there.

> tried xeus-robot 

I see some lovely things happening there, but yeah, I like the toys we have over here. 

> playground demo

As you mention playgrounds... we've been hustling on [jupyterlite](https://github.com/jtpio/jupyterlite) to reboot what was started on jyve and a few other places: a purely client-side implementation of lab and all the relevant server pieces. Given that robot is still blissfully low-dependency, and something like IPython/xeus will eventually be part of that stack, i would not rule out our ability to deliver a working robot kernel playground served from the browser, the diagram stuff, video chat, etc. It'll come.

> your old RF Blocky demo.

Aw, man, they've done so much cool stuff with that since I worked with it last. I need to warm jupyterlab-outsurce back up for lab 3. Now that I've paid the price on really groking custom comms (the underbelly of jupyter widgets) and the split renderers on drawio, I could see using the new libdoc JSON (or LSP, or something) to build really nice blocks automatically at runtime. Or maybe it's _not_ blockly at all, but drawio, which would provide the right UI and data format.

**Comment by datakurre** [comment]
As always, I am speechless about all the progress happening around Jupyter... :see_no_evil:

**Comment by bollwyvl** [comment]
It's definitely going... places.

In today's community call (should be up on YouTube soon), there were demos
of jupyterlite (kernels in the browser... Yes, robot works) and nbterm
(notebooks in the terminal).

The real challenge is in creating and maintaining community-driven
protocols and formats that ensure all this stuff works together today and
for the foreseeable future, while still allowing for innovation!
